LTW2/HelloGroup2/Models/ErrorViewModel.cs
namespace HelloGroup2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LTW2/HelloGroup2/Controllers/HomeController.cs
using HelloGroup2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HelloGroup2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LTW2/HelloGroup2/Controllers/MathController.cs
using Microsoft.AspNetCore.Mvc;

namespace HelloGroup2.Controllers
{
    public class MathController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add(long a, long b)
        {
            long c = a + b;
            MathResult mathResult = new MathResult
            {
                A = a,
                B = b,
                C = c,
                Message = $"Tổng của {a} và {b} là {c}"
            };
            return View(mathResult);
        }
    }
    public class MathResult
    {
        public long A { get; set; }
        public long B { get; set; }
        public long C { get; set; }
        public string Message { get; set; }
    }
}

LTW2/HelloGroup2/Views/Math/Add.cshtml
@model HelloGroup2.Controllers.MathResult

<h1>Kết quả phép cộng</h1>
<p>
    @Model.Message
</p>
<a class="btn btn-success" asp-action="Index" asp-controller="Math">
    <i class="fa-solid fa-arrow-left"></i> Quay lại</a>

LTW2/HelloGroup2/Views/Math/Index.cshtml
<h1>Một số phép toán cơ bản</h1>
<form asp-action="Add" method="get">
    <div class="row">
        <div class="col-3">
            <label>a</label>
        </div>
        <div class="col-9">
            <input type="text" name="a" placeholder="Nhập a" />
        </div>

        <div class="col-3">
            <label>b</label>
        </div>
        <div class="col-9">
            <input type="text" name="b" placeholder="Nhập b" />
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-success">Tổng</button>
        </div>
        <div class="col-12">

        </div>
    </div>
</form>

LTW2/HelloGroup2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelloGroup2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelloGroup2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelloGroup2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Math" asp-action="Index">Math</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Nhóm 2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>